import requests
import time
import socket
import random
from datetime import datetime, timezone
from concurrent.futures import ThreadPoolExecutor, as_completed
from urllib.parse import parse_qs
import os

# ============== SOURCES ==============
SOURCES = [
    "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-CIDR-RU-all.txt",
    "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/Vless-Reality-White-Lists-Rus-Mobile-2.txt",
    "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/Vless-Reality-White-Lists-Rus-Mobile.txt",
    "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-CIDR-RU-checked.txt",
    "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-SNI-RU-all.txt",
    "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/BLACK_VLESS_RUS_mobile.txt",
    "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/BLACK_VLESS_RUS.txt",
]

EXCLUDE_COUNTRIES = {"🇮🇷", "🇷🇺", "🇨🇳", "🇹🇷", "IR", "RU", "CN", "TR"}
TOP_N = 100

# ================== HELPER FUNCTIONS ==================
def should_exclude(config: str) -> bool:
    try:
        remark = config.split('#')[-1].upper()
        return any(c in remark for c in EXCLUDE_COUNTRIES)
    except:
        return False


def extract_host_port(cfg: str):
    """Minimal parser - only needs host:port for TCP test"""
    try:
        url_part = cfg.split('#')[0]
        if not url_part.startswith('vless://'):
            return None, None
        without_scheme = url_part[8:]
        if '@' not in without_scheme:
            return None, None
        _, rest = without_scheme.split('@', 1)
        hostport_part = rest.split('?')[0].split('/')[0]
        if ':' in hostport_part:
            host, port_str = hostport_part.rsplit(':', 1)
            port = int(port_str)
        else:
            host = hostport_part
            port = 443
        return host.strip(), port
    except:
        return None, None


def test_node(cfg: str):
    """Very light test: only TCP connect (much higher success rate)"""
    host, port = extract_host_port(cfg)
    if not host or not port:
        return cfg, 99999

    start_time = time.time()
    try:
        with socket.create_connection((host, port), timeout=8.0) as sock:
            pass  # TCP connect successful
        latency = round((time.time() - start_time) * 1000, 1)
        return cfg, latency
    except Exception:
        return cfg, 99999


def generate_subscription() -> str:
    print("🔄 Fetching ALL VLESS nodes from sources...")
    configs = []

    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) VLESS-Checker/2.4"}

    for url in SOURCES:
        try:
            resp = requests.get(url, timeout=20, headers=headers)
            resp.raise_for_status()
            for line in resp.text.splitlines():
                line = line.strip()
                if line.startswith('vless://') and not should_exclude(line):
                    configs.append(line)
        except Exception as e:
            print(f"⚠️ Source failed: {url} → {e}")

    configs = list(dict.fromkeys(configs))  # remove duplicates
    print(f"📥 Loaded {len(configs)} unique VLESS configs")

    # === Light TCP ping test on all nodes ===
    print(f"⚡ Testing {len(configs)} nodes (simple TCP connect)...")
    tested = []
    with ThreadPoolExecutor(max_workers=80) as executor:
        futures = [executor.submit(test_node, c) for c in configs]
        for future in as_completed(futures):
            cfg, latency = future.result()
            if latency < 99999:   # only nodes that responded
                tested.append((cfg, latency))

    tested.sort(key=lambda x: x[1])   # sort by lowest ping first

    good_nodes = [cfg for cfg, lat in tested]
    print(f"✅ Found {len(good_nodes)} active nodes (TCP responded)")

    # Fallback if literally zero nodes responded
    if not good_nodes:
        print("⚠️ No nodes responded to TCP test → using all loaded configs")
        good_nodes = configs

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    random_id = random.randint(1000, 9999)   # forces change every run

    header = f"""# profile-title: 🚀 VLESS Nodes (Ping Tested - GitHub Auto)
# profile-update-interval: 6
# Generated: {now}
# Random-ID: {random_id}   ← (this forces update every run)
# Total Nodes Tested: {len(configs)}
# Active Nodes Found: {len(good_nodes)}
# Test: Simple TCP connect (very lenient)
# Sorted by: Lowest ping first
# Auto-generated by GitHub Actions
"""

    final_nodes = good_nodes[:TOP_N]
    print(f"📤 Final subscription ready with {len(final_nodes)} nodes")
    return header + "\n".join(final_nodes)


if __name__ == "__main__":
    print("🚀 Starting VLESS Subscription Updater")
    subscription = generate_subscription()

    filename = "subscription.txt"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(subscription)

    print(f"✅ Successfully wrote {filename} with {subscription.count('vless://')} VLESS nodes")
